# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"        background-image: url(:/images/background.svg);\n"
"        background-position: center;\n"
"        background-color: #061f47;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.console = QtWidgets.QTextBrowser(self.centralwidget)
        self.console.setEnabled(False)
        self.console.setGeometry(QtCore.QRect(0, 0, 801, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setStyleSheet("background: transparent; padding: 30px;\n"
"font-size: 16px;")
        self.console.setLineWidth(1)
        self.console.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.console.setAcceptRichText(True)
        self.console.setObjectName("console")
        self.container = QtWidgets.QWidget(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(20, 410, 761, 171))
        self.container.setStyleSheet("background-color: rgba(5,5,5,0.4); border-radius: 5px;\n"
"color: #92d3ff;\n"
"font-size: 16px;")
        self.container.setObjectName("container")
        self.startBotButton = QtWidgets.QPushButton(self.container)
        self.startBotButton.setGeometry(QtCore.QRect(580, 50, 151, 61))
        self.startBotButton.setStyleSheet("background-color: rgba(34, 111, 237, 0.7); border-radius: 5px;\n"
"color: #b3e0ff;")
        self.startBotButton.setObjectName("startBotButton")
        self.scriptFileButton = QtWidgets.QPushButton(self.container)
        self.scriptFileButton.setGeometry(QtCore.QRect(180, 30, 161, 41))
        self.scriptFileButton.setStyleSheet("background-color: rgba(34, 111, 237, 0.7);border-radius: 5px;\n"
"color: #b3e0ff;")
        self.scriptFileButton.setObjectName("scriptFileButton")
        self.label = QtWidgets.QLabel(self.container)
        self.label.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.label.setToolTipDuration(-1)
        self.label.setStyleSheet("background: none;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.container)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 111, 21))
        self.label_2.setStyleSheet("background: none;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.messageDurationBox = QtWidgets.QLineEdit(self.container)
        self.messageDurationBox.setGeometry(QtCore.QRect(180, 100, 161, 41))
        self.messageDurationBox.setStyleSheet("background-color: rgba(34, 111, 237, 0.2); padding: 5px; border-radius: 5px;\n"
"border: none;")
        self.messageDurationBox.setAlignment(QtCore.Qt.AlignCenter)
        self.messageDurationBox.setObjectName("messageDurationBox")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(760, 10, 31, 31))
        self.closeButton.setStyleSheet("border: none;\n"
"color: rgba(34, 111, 237, 0.7);\n"
"font-size: 40px;")
        self.closeButton.setIconSize(QtCore.QSize(16, 16))
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OptiBot 0.1.1"))
        self.console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.startBotButton.setText(_translate("MainWindow", "Start Bot"))
        self.scriptFileButton.setToolTip(_translate("MainWindow", "Please select a file"))
        self.scriptFileButton.setText(_translate("MainWindow", "Select Script File"))
        self.label.setText(_translate("MainWindow", "File to Spam"))
        self.label_2.setText(_translate("MainWindow", "Message Delay"))
        self.messageDurationBox.setToolTip(_translate("MainWindow", "Enter a value or a range separated with \"-\" to randomize send delay"))
        self.messageDurationBox.setText(_translate("MainWindow", "60-80"))
        self.closeButton.setText(_translate("MainWindow", "×"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
